[package]
name = "trol"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rand = "0.9.2"
serenity = "0.12.4"
tokio = { version = "1.46.1", features = ["rt-multi-thread"] }
once_cell = "1.21.3"
